name: Update Terraform Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Update Terraform Docs
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
      - name: Commit changes to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
