name: Create a Release

on:
  push:
    branches: [ main ]

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Get latest commit hash
        id: latest_commit
        run:  echo COMMIT=`git log -1 --pretty=format:"%H"` >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Commit ID : ${{ steps.latest_commit.outputs.COMMIT }}
          draft: false
          prerelease: false
